<?php
$this->headScript()->appendFile($this->assetUrl('js/metadata-browse.js', 'MetadataBrowse'));
//$this->headLink()->appendStylesheet($this->assetUrl('css/metadata-browse.css', 'MetadataBrowse'));
$this->htmlElement('body')->appendAttribute('class', 'sidebar-open');

?>


<?php echo $this->pageTitle($this->translate('Metadata Browse · Settings')); ?>
<script type='text/javascript'>
    var filteredPropertyIds = <?php echo $filteredPropertyIds; ?>
</script>

<?php echo $this->form()->openTag($form); ?>

<div id='properties'>
    <p>
        <?php echo $this->translate("Choose properties from the sidebar to be searchable"); ?>
    </p>
</div>
<?php echo $this->partial('metadata-browse/property-template'); ?>

<fieldset id='page-actions'>
    <button type="submit"><?php echo $this->translate('Save'); ?></button>
</fieldset>

<p>
hi
<?php echo $this->translate("If checked, the properties selected below will be linked on the admin side, overriding all site-specific settings. Each site's own settings will be reflected on the public side. Otherwise, the admin side will reflect the aggregated settings for all sites; anything selected to be a link in any site will be a link on the admin side."); ?>
</p>
<?php echo $this->formCollection($form, false); ?>

<?php echo $this->form()->closeTag($form); ?>

<div class='sidebar active'>
<?php echo $this->propertySelector('Select properties to be searchable'); ?>
</div>
